SampleFileName : Rental_Bike_Share_Data_20180101_120000.csv
LengthOfDateStampInFile : 8
LengthOfTimeStampInFile : 6
NumberofColumns : 15
Columns : 
  date  : datetime
  month : int
  year  : int
  hour  : int
  season : category
  weekday : category
  is_holiday : category
  working_day : category
  temperature(in celcius) : float
  relative_temperature(in celcius) : float
  wind_speed(in kmph) : float
  humidity(in %) : float
  description : varchar
  casual : int
  member : int
  
target_column: total_count

date_columns:
  - date
  - year
  - month
  - hour

numerical_columns:
  - temp
  - wind
  - humidity
  
categorical_columns:
  - season
  - weekday
  - is_holiday
  - working_day
  - weather_sit
  - is_covid